:gift: Add FORCE_COLOR support
fatih/color pull request #156
Opened 2022-01-26 21:09 UTC by cardil

Fixes #155

2022-07-09 21:44 UTC, cardil commented
/cc @fatih 

Can I ask you for a review? 🙏

2022-10-11 21:47 UTC, aaronshurley commented
@fatih +1, we have a project that would love to see this capability merged (and released 😁).

2022-11-14 22:41 UTC, pellared requested changes
I also disagree that this functionality should be merged

2022-11-14 22:41 UTC, pellared commented on color.go
> +			return colorMode(mode)
undocumented functionality (nor in `README.md` nor in doc comments)

2023-01-18 17:31 UTC, fatih commented
Sorry for the late response. But this feature adds complexity that I'm not willing to maintain in the long run. 

Forcing color is something that library importers can easily add themselves. I'll evaluate it in the future again if this becomes a standard in the industry (and by standard, I mean it's widely used). 

@cardil thanks for you work though, and I hope you understand why I don't want to merge.

2023-01-18 17:31 UTC, closed without merging